(load "lib/scheme/lib.scm")

(set-tick-speed 300)

(define BASE-OFF 21)
(define interval 2)
(define acc1 0)
(define acc2 8)
(define acc3 0)
(define acc4 0)
(define off 0)
(define len 4)

(define (f1)
    (define n (mode-get 0 1 (+ (* acc1 interval) BASE-OFF off)))
    (n-on 0 n 127)
    (when (= acc1 0)
      ; (dbg (string-append "bass: " (number->string n)))
      (n-on 1 (- n 12) 127)
    )
    (when (= acc1 (/ acc2 2))
      ; (dbg "sec")
      (n-on 2 (mode-get 0 1 (+ BASE-OFF 4 off)) 127)
    )
    (when (= acc1 (- acc2 (/ acc2 4)))
      ; (dbg "sec2")
      (n-on 2 (mode-get 0 1 (+ BASE-OFF 3 off)) 127)
    )
    ; (dbg (string-append "tick: " (number->string acc1)))
    ; (dbg (string-append "note: " (number->string n)))
    (set! acc1 (+ 1 acc1))
    (when (= acc1 acc2) 
      (set! acc1 0)
      (set! acc3 (+ acc3 1))
      (when (= acc3 2)
        (set! acc2 (* len (rng->gen-range 1 4)))
        (set! off (rng->gen-range 0 7))
        (set! acc3 0)
        (set! acc4 (+ acc4 1))
      )
      ; (dbg (number->string acc2))
    )
)

(define (f2)
    (define n (mode-get 0 1 (+ (* (- acc2 acc1) interval) BASE-OFF off)))
    (n-on 0 n 127)
    (when (= acc1 0)
      ; (dbg (string-append "bass: " (number->string n)))
      (n-on 1 (- n 12) 127)
    )
    (when (= acc1 (/ acc2 2))
      ; (dbg "sec")
      (n-on 2 (mode-get 0 1 (+ BASE-OFF 5 off)) 127)
    )
    (when (= acc1 (- acc2 (/ acc2 4)))
      (dbg "sec2")
      (n-on 2 (mode-get 0 1 (+ BASE-OFF 4 off)) 127)
    )
    ; (dbg (string-append "tick: " (number->string acc1)))
    ; (dbg (string-append "note: " (number->string n)))
    (set! acc1 (+ 1 acc1))
    (when (= acc1 acc2) 
      (set! acc1 0)
      (set! acc3 (+ acc3 1))
      (when (= acc3 2)
        (set! acc2 (* len (rng->gen-range 1 4)))
        (set! off (rng->gen-range 0 7))
        (set! acc3 0)
        (set! acc4 (+ acc4 1))
      )
      ; (dbg (number->string acc2))
    )
)

(define (tick)
  (when (< acc4 5) (f1))
  (when (>= acc4 5) (f2))
  (when (>= acc4 10) 
    (set! acc4 0)
    (set! len (rng->gen-range 3 5))
    ; (dbg (string-append "len: " (number->string len)))
  )
)
