(load "lib/scheme/lib.scm")

(define split string-split-space)

(set-tick-speed 200)

(define t 0)

(define empty  (split "r"))
(define kick1  (split "1 r r r 1 r r r"))
(define kick2  (split "1 r r r 1 r r r 1 r r r 1 r r 1"))
(define snare1 (split "r r 1 r r r 1 r"))
(define snare2 (split "r r 1 r r r 1 1"))
(define hat1   (split "r 1 r 1 r 1 r 1 r 1 r 1 r 1 1 1"))
(define hat2   (split "r 1 1 1 r 1 r 1 r 1 r 1 r 1 1 1"))
(define bass1  (split "r 0 r 0 r 0 r 0"))
(define bass2  (split "r 0 r 0 r 0 r 1"))

(define kick kick1)
(define snare snare1)
(define hat hat1)
(define bass bass1)

(define (seq notes interval)
  (list-ref notes (modulo interval (length notes))))

(define (n-on ch n)
  (if (not (string=? n "r"))
    (midi-note-on ch (modal 0 1 (+ 21 (string->number n))) 127)
    (debug "rest")
  )
)

(define (tickfn)
  (debug (number->string t))
  (when (= t 0)
    (set! kick kick1)
    (set! snare snare1)
    (set! hat empty)
    (set! bass bass1)
  )
  (when (= t 32) 
    (set! kick kick2)
    (set! snare snare2)
    (set! hat empty)
    (set! bass bass2)
  )
  (when (= t 64)
    (set! kick kick1)
    (set! snare snare1)
    (set! hat hat1)
    (set! bass bass1)
  )
  (when (= t 96) 
    (set! kick kick2)
    (set! snare snare2)
    (set! hat hat2)
    (set! bass bass2)
  )
  (n-on 0 (seq kick t))
  (n-on 1 (seq snare t))
  (n-on 2 (seq hat t))
  (n-on 3 (seq bass t))
  (set! t (modulo (+ 1 t) 128))
)
